### PR TITLE
Added npm and yarn jobs to the github actions workflow

### PR DESCRIPTION
**Pull request by asadmansr**
# Description

In reference to issue https://github.com/cjwilburn/dank-memes/issues/84, I have enhanced the github actions workflow by adding a npm and yarn job that checkouts the code, installs the dependencies, tests and runs the application. During this process, I am also generating the config.json file dynamically with the secrets stored in the GitHub actions workflow. The build is passing currently. If you like me to make any changes or implement anything else, let me know. Thanks

## Steps to Test

I added secrets and push the changes to my repository and the pipeline was passing. 

## Screenshots

N/A

## Deploy Notes

To use your own username and password, just secrets the username and password secrets under the repository's secrets. 

## Checklist

- [x] I have tested these code changes and included the relevant urls and screenshots.
- [x] I have updated our build tasks accordingly (if applicable).
- [x] I have updated our documentation accordingly (if applicable).
- [x] I have linted the code that I've included in this PR (if applicable).
- [x] My code follows the code style of this project.
- [x] My code is ready for review.

### CODE REVIEW

**Comment by asadmansr** [comment]
You can see the github actions workflow run on my fork: https://github.com/asadmansr/dank-memes/actions/runs/292271849

We can change the github action workflow to also run checks on PR. Would you like me to change that?

**Review by cjwilburn — APPROVED** [review]
LGTM!

**Comment by cjwilburn** [comment]
If you'd like to add run checks on PR, please do @asadmansr. Thank you.

**Comment by asadmansr** [comment]
Thank you @cjwilburn. I have updated the PR with this last change. We now run validation on pull requests as well. As you can see, both checks have passed!

This PR counts as one of my contributions for Hacktoberfest. To keep my contribution valid, could you keep the `hacktoberfest` topic on your repository until November 4? If not, you can also label this PR as `hacktoberfest-accepted`. [More information can be found here](https://hacktoberfest.digitalocean.com/hacktoberfest-update). Thank you!

**Review by cjwilburn — APPROVED** [review]

**Pull request merged**
