### PR TITLE
Refactor meme files to generators

### PR DESCRIPTION
**Pull request by justintucker**
Addresses issue #74 

# Description
- Refactors remaining meme scripts to generator pattern
- Cleans up .gitignore and extra editor files
- Removes yarn lock file in favor of package-lock.json

## Steps to Test
Run test script. All tests should pass.

## Checklist

- [x] I have tested these code changes and included the relevant urls and screenshots.
- [ ] I have updated our build tasks accordingly (if applicable).
- [ ] I have updated our documentation accordingly (if applicable).
- [x] I have linted the code that I've included in this PR (if applicable).
- [x] My code follows the code style of this project.
- [x] My code is ready for review.

### CODE REVIEW

**Comment by justintucker** [comment]
@cjwilburn It looks like we may want to keep the `yarn.lock` file after reading through some of the other issues. I can revert that commit if you think it should stay.

**Comment by justintucker** [comment]
@cjwilburn I wonder if the hacktoberfest label is case sensitive or some other setting has to be changed. For this PR, I'm seeing the following in my dashboard: 
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Review by cjwilburn — APPROVED** [review]
Thank you so much @justintucker !!! LGTM.
tenor-228697233

**Comment by cjwilburn** [comment]
@justintucker do you still see this in your dashboard?

**Comment by justintucker** [comment]
@cjwilburn Looks like it's updated now. Thanks!

**Pull request merged**
